backend:
  name: github
  repo: areyouinlovetim/Timbynumproductions-site 
  branch: main
  base_url: https://api.netlify.com
  auth_endpoint: auth

site_url: "https://timbynumproductions.netlify.app"
media_folder: "assets"
public_folder: "/assets"
